export const CODE_BLOCK_LANGUAGES = {
  text: 'Plain text',
  txt: 'Plain text',
  plaintext: 'Plain text',
  plain: 'Plain text',
  js: 'JavaScript',
  javascript: 'JavaScript',
  mjs: 'JavaScript (ESM)',
  cjs: 'JavaScript (CommonJS)',
  jsx: 'JavaScript (React)',
  ts: 'TypeScript',
  typescript: 'TypeScript',
  tsx: 'TypeScript (React)',
  json: 'JSON',
  jsonc: 'JSONC',
  bash: 'Bash',
  sh: 'Shell',
  shell: 'Shell',
  zsh: 'Zsh',
  html: 'HTML',
  css: 'CSS',
  scss: 'SCSS',
  less: 'Less',
  md: 'Markdown',
  markdown: 'Markdown',
  yaml: 'YAML',
  yml: 'YAML',
  py: 'Python',
  python: 'Python',
  rs: 'Rust',
  rust: 'Rust',
  go: 'Go',
  java: 'Java',
  c: 'C',
  cpp: 'C++',
  cxx: 'C++',
  cc: 'C++',
  cs: 'C#',
  csharp: 'C#',
  php: 'PHP',
  rb: 'Ruby',
  ruby: 'Ruby',
  swift: 'Swift',
  kt: 'Kotlin',
  kotlin: 'Kotlin',
  sql: 'SQL',
  lua: 'Lua',
  xml: 'XML',
  toml: 'TOML',
  ini: 'INI',
  dockerfile: 'Dockerfile'
} as const

export type CodeBlockLanguage = keyof typeof CODE_BLOCK_LANGUAGES
